APP_ENV=local
APP_DEBUG=true
APP_KEY=e2e017a3db133bddd458f62d02f70919

DB_HOST=localhost
DB_DATABASE=wplaravel.dev
DB_USERNAME=root
DB_PASSWORD=

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

MAIL_DRIVER=smtp
MAIL_HOST=smtp.google.com
MAIL_PORT=2525
MAIL_USERNAME=emtapseo@gmail.com
MAIL_PASSWORD=anhphong12
